include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_relative_imports: true
    always_use_package_imports: false
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    sort_constructors_first: true
    unawaited_futures: true
    unnecessary_lambdas: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/*.gr.dart"
    - "**/l10n/generated/**"
    - "**/generated/**"
  errors:
    invalid_annotation_target: ignore
